"""
This program is used to generate an html file with a list of randomly-selected winners.
It can be used for giveaways, raffles, etc. so long as the input csv is properly
formatted (for now).

Todo:
    * Add args to select a specified column.
    * Improve docstrings. Some of the phrasing used in the docstrings are...bad.
    * Write a readme for easier usage.

"""
import csv
import random
import argparse
def gen_list(argcsv):
    """
    This function generates the list of possible winners to be passed into html_writer().

    Args:
        argcsv - csv file from parse_args() to read and pull the list of possible winners from
    Returns:
        winlist - the list of possible winners. It takes in the ticketholder's
        username and ticketnumber and appends them before inserting them into
        winlist to be passed to html_writer()

    """
    winlist = []
    with open(argcsv) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            username = row['What username do you go by online?']
            if row['What username do you go by online?'] == '-':
                username = row['Ticket First Name']
            winlist.append(row['Number'] + " " +  username)
    return winlist
def html_writer(winlist, total_winners):
    """
    This function writes the html file to display the winners.

    Args:
        winlist - list of winners generated by gen_list()
        total_winners - total number of specified winners taken from command line args

    Returns:
        None. Writes an html file.

    """
    slide = open('winners.html', 'w')
    slide.write("""
    <!doctype html>
    <html lang=en>
    <head>
    <meta charset=utf-8>
    <title>SMKmeetup Giveaway Winners!</title>
    <link rel="stylesheet" href="raffle-style.css">
    </head>
    <body>
    <h2>SMKmeetup Giveaway Winners</h2>
    <ul class="multi-12">
    """)
    for i in random.sample(winlist, len(winlist))[0:total_winners]:
        winner = i[:12] + (i[12:] and '...')
        slide.write("<li>"+winner+"</li>\n")
    slide.write("""
    </ul>
    </body>
    </html>
    """)
    slide.close()
def parse_args():
    """
    This function parses the arguments from the command line.

    Args:
        None

    Returns:
        args object to be passed to other functions

    """
    parser = argparse.ArgumentParser()
    parser.add_argument("csv", help="the location of the csv input")
    parser.add_argument("total_winners", type=int, help="total number of selected winners")
    return parser.parse_args()
def main():
    """
    This function calls all the necessary functions needed for the program to run.
    """
    args = parse_args()
    html_writer(gen_list(args.csv), args.total_winners)
if __name__ == "__main__":
    main()
